@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "Implement Save Project with Artist field"
echo Pushing to GitHub...
git push origin main
echo Done! Vercel deployment should trigger automatically.
pause
