@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "Add Custom Cover Image Upload to Save Project"
echo Pushing to GitHub...
git push origin main
echo Done! Vercel deployment should trigger automatically.
pause
