@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "Update: Waveform Editor & Track Renaming"
echo Pushing to GitHub...
git push origin main
echo Done! Vercel deployment should trigger automatically.
pause
